# Generated by Django 4.2.3 on 2024-01-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brgy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brgy_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('contact_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Graduated', 'Graduated')], max_length=100)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScholarsApp.brgy')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScholarsApp.course')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScholarsApp.municipality')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScholarsApp.school')),
            ],
        ),
    ]
